require 'csv'
  # header = [
  #   'Sender',
  #   'Receiver', 
  #   'PO Number', 
  #   'Release Number',
  #   'PO Date',
  #   'Terms Info',
  #   'FOB Info',
  #   'Ship-To Name',
  #   'Ship-To Address 1',
  #   'Ship-To Address 2',
  #   'Ship-To Location',
  #   'Ship-To City',
  #   'Ship-To State',
  #   'Ship-To Postal Code',
  #   'Ship-To Country',
  #   'Ship-To Contact',
  #   'Bill-To Name',
  #   'Bill-To Address 1',
  #   'Bill-To Address 2',
  #   'Bill-To Location',
  #   'Bill-To City',
  #   'Bill-To State',
  #   'Bill-To PostalCode',
  #   'Bill-To Country',
  #   'Bill-To Contact',
  #   'hdr_user_defined_field1',
  #   'hdr_user_defined_field2',
  #   'hdr_user_defined_field3',
  #   'hdr_user_defined_field4',
  #   'hdr_user_defined_field5',
  #   'hdr_user_defined_field6',
  #   'hdr_user_defined_field7',
  #   'hdr_user_defined_field8',
  #   'hdr_user_defined_field9',
  #   'hdr_user_defined_field10',
  #   'hdr_user_defined_field11',
  #   'hdr_user_defined_field12',
  #   'hdr_user_defined_field13',
  #   'hdr_user_defined_field14',
  #   'hdr_user_defined_field15',
  #   'hdr_user_defined_field16',
  #   'hdr_user_defined_field17',
  #   'hdr_user_defined_field18',
  #   'hdr_user_defined_field19',
  #   'hdr_user_defined_field20',
  #   'Notes',
  #   'Line Nbr',
  #   'Supplier Item Nbr',
  #   'Item Description',
  #   'Quantity',
  #   'Unit Price',
  #   '"UOM  Basis of UOM"',
  #   'Buyer Item Nbr',
  #   'Manufacturer Item Nbr',
  #   'dtl_user_defined_field1',
  #   'dtl_user_defined_field2',
  #   'dtl_user_defined_field3',
  #   'dtl_user_defined_field4',
  #   'dtl_user_defined_field5',
  #   'dtl_user_defined_field6',
  #   'dtl_user_defined_field7',
  #   'dtl_user_defined_field8',
  #   'dtl_user_defined_field9',
  #   'dtl_user_defined_field10',
  #   'dtl_user_defined_field11',
  #   'dtl_user_defined_field12',
  #   'dtl_user_defined_field13',
  #   'dtl_user_defined_field14',
  #   'dtl_user_defined_field15',
  #   'dtl_user_defined_field16',
  #   'dtl_user_defined_field17',
  #   'dtl_user_defined_field18',
  #   'dtl_user_defined_field19',
  #   'dtl_user_defined_field20',
  #   'PO Purpose',
  #   'SAC Info',
  #   'Delivery Date Requested',
  #   'Last Delivery Date Requested',
  #   'Sub-Line Item',
  #   'Item Info'
  # ]
FactoryGirl.define do
  factory :import_file, :class => Tempfile do  
    to_create {}  

    initialize_with do
      create_import_file([{:lines => [{}]}])
    end
  end
end
